stages:
  - testing
  - reports
  - deploy

setup_job:
  stage: testing
  image: python:3.12.3-slim
  script:
    - pip install poetry
    - poetry install
    - poetry run playwright install
    - poetry run pre-commit install
    - poetry run pre-commit run --all-files
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
      - .venv/

ui_tests:
  stage: testing
  image: python:3.12.3-slim
  dependencies:
    - setup_job
  script:
    - poetry run pytest --alluredir=allure-results ./tests/ui -n=4
  allow_failure: true
  artifacts:
    paths:
      - allure-results/ui
    expire_in: 1 day

api_tests:
  stage: testing
  image: python:3.12.3-slim
  dependencies:
    - setup_job
  script:
    - poetry run pytest --alluredir=allure-results ./tests/api -n=4
  allow_failure: true
  artifacts:
    paths:
      - allure-results/api
    expire_in: 1 day

allure_report:
  stage: reports
  image: frankescobar/allure-docker-service
  dependencies:
    - ui_tests
    - api_tests
  script:
    - allure generate -c ./allure-results -o ./allure-report
  artifacts:
    paths:
      - ./allure-results
      - ./allure-report
      
deploy_job:
  stage: deploy
  dependencies:
    - allure_report
  script:
    - mkdir public
    - mv ./allure-report/* public
  artifacts:
    paths:
      - public
  rules:
    - when: always