[pytest]
addopts = -sv --alluredir allure-results --junitxml reports/junit-report.xml --strict-markers
# addopts = -sv --junitxml reports/junit-report.xml --strict-markers

filterwarnings =
    ignore::UserWarning:pydantic._migration

markers =
    api: pytest mark used for API tests
    ui: pytest mark used for UI tests
    db: pytest mark used for database tests
    smoke: pytest mark used for Smoke tests
    regression: mark test as part of regression suites
    dependency: mark test as dependent on another test
    qase: mark test with Qase test case ID

junit_family=legacy