env_name: dev

ui:
  base_url: https://dev.pretty-py.andersenlab.dev  
  browser: chromium
  headless: false
  slow_mo: 300

api:
  base_url: https://api-dev.pretty-py.andersenlab.dev  
  timeout: 10

timeouts:
  page_load: 30
  assertion: 5

features:
  enable_experimental: true
