env_name: prod

ui:
  base_url: https://prod.pretty-py.andersenlab.dev  
  browser: chromium
  headless: true
  slow_mo: 0

api:
  base_url: https://api-prod.pretty-py.andersenlab.dev 
  timeout: 5

timeouts:
  page_load: 15
  assertion: 3

features:
  enable_experimental: false
